server:
  port: 8888
person:
  lastName: zhangsan${random.uuid} #随机的一个uuid
  age: ${random.int}
  boss: false
  birth: 2018/12/12
  maps:
    k1: v1
    k2: v2
  lists:
    - lisi
    - wangwu
    - zhaoliu
  dog:
    name: ${person.hello:hello}小狗  #如果person.hello 取不出来值，就会按照后面的默认值走
    age: 12
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
server:
  port: 8080





---
spring:
  profiles: pro
server:
  port: 6666